### ISSUE TITLE
How to make parallax cell not effect text?

### ISSUE THREAD

**Issue by JayceBryce** [KelvinJin/AnimatedCollectionViewLayout#48]
Right not it seems like the Parallax effects the background of the cell and what's in front. I was wondering if there is a way to change this so the text on the cell is not effected by Parallax? Therefore the "Text/UILabel" does not move with the Parallax as you scroll?

**Comment by KelvinJin** [comment]
I'm not 100% sure if I understand you. If you could provide some sort of illustration that would be nice.

Regardless, your assumption is correct. The parallax effect this library provides is by moving the `contentView` of the cell slower (hence travel longer) than the cell itself. So basically if you have two elements say a label and an icon, you can put one in the `contentView` and another in `backgroundView` and what you'll get is that the one in the `contentView` will move slower (the parallax effect) and the one in the `backgroundView` will move together with the cell.

In your case, if you want some text not moving with the parallax then putting it in the `backgroundView` instead of `contentView`.

**Comment by JayceBryce** [comment]
@KelvinJin Thanks for replying. I am using your sample project and here is an illustration of what I mean:

<img width="683" alt="parallax" src="https://user-images.githubusercontent.com/37093552/55526549-8d118f00-5663-11e9-8846-d00ca40610ae.png">

In your sample project, both the `textLabel` and background color is in the `contentView`. Because of this everything has the parallax effect. 

You said above that I can add items to a `backgroundView` and that will not have the parallax effect. I am not sure how to do this. How would you put the `textLabel` outside of the `contentView` so it has no parallax effect? Please use your sample project as an example.

**Comment by KelvinJin** [comment]
Check `parallax-demo` branch. It's all about how much you know about UICollectionViewCell to be honest.
