### ISSUE TITLE
How to adjust collectionView Cell size appropriately when in landscape?

### ISSUE THREAD

**Issue by JayceBryce** [KelvinJin/AnimatedCollectionViewLayout#49]
I'm using your current projects master branch. When I run the project the Parallax Collection view in portrait it looks great. The issue is when I turn it landscape the cells do not resize property( The experience should be the same as portrait - only one cell showing). Could you please fix this issue on a separate branch? Thank you!

Here is an image illustrating the issue:

![Parallax-Image](https://user-images.githubusercontent.com/37093552/55655010-e80cc880-57c0-11e9-837f-9394269b94a7.jpg)

**Comment by KelvinJin** [comment]
Hey, you'll need to change `scrollDirection` to horizontal when rotate to landscape...

**Comment by JayceBryce** [comment]
Currently it is set to horizontal. When I flip the phone to landscape it remains .horizontal but everything seems to break like the image above. Am I misunderstanding something? Thanks 

```
        let layout = AnimatedCollectionViewLayout()
        layout.scrollDirection = .horizontal
        layout.animator = ParallaxAttributesAnimator()
        collectionView.collectionViewLayout = layout
```

**Comment by KelvinJin** [comment]
This issue is again not related to this library at all. You'll need to call `collectionViewLayout.invalidateLayout()` in `viewWillTransition`. You can find plenty of answers in StackOverflow. And you might also need to fix the issue caused by contentOffset after rotation which is another issue.

I suggest you try without using `AnimatedCollectionViewLayout` first and see if it's an issue with the library itself before posting any issue.

**Comment by boominadhaprakash** [comment]
Hi @JayceBryce
Have you fixed that issue. I am also facing that.

**Comment by OsamaMukhtar** [comment]
Same issue here
